### PR TITLE
Add SmartCamera Module

### PR DESCRIPTION
**Pull request by jmachuca77**
This pull requests adds the smart camera module used to connect and control cameras. Currently it supports the Sony QX series cameras, and has also a class for a webcam (untested).

### CODE REVIEW

**Comment by gmorph** [comment]
Tridge, this can be merged as the common code changes in "mavproxy_cmdlong.py" and "setup.py" are all good and the other changes are specific to the smart_camera module.
Thanks, Grant.

**Comment by jmachuca77** [comment]
Added a few more commits to fix a few issues inside the smart camera module.

**Comment by gmorph** [comment]
Hi Jaime.  We need to catch up on this pull request.  The changes in the resulting 10 files are fine.  Its just all the git merges in between we need to get rid of.  Jump into mumble when you can and we will go through it.  
Thanks, Grant.

**Comment by jmachuca77** [comment]
Created a new pull request #137 with a cleaner commit history.

**Pull request closed without merging**
